<a href="https://colab.research.google.com/github/debasish-dutta/DL-with-Pytorch/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1AXMy2DWMF0vtTtMsNN81_aNG2QOqQXEb')

# 5 interesting torch functions

An short introduction about PyTorch and about the chosen functions. 

- torch.arange
- torch.logspace
- torch.cat
- torch.reshape
- torch.normal

Before we begin, let's install and import PyTorch

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.range

torch.range(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

Returns a 1-D tensor of size [start-end/step] + 1 

In [ ]:
t1 = torch.arange(1, 5)
t1

tensor([1, 2, 3, 4])

Explanation about example

In [ ]:
t2 = torch.arange(1, 10, 2)
t2

tensor([1, 3, 5, 7, 9])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(10, 2, 2)

RuntimeError: ignored

Explanation about example

Closing comments about when to use this function
This function is particularly helpfull when creating a tensor using the same funtionality as python range function.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ddmasterdon/01-tensor-operations


'https://jovian.ai/ddmasterdon/01-tensor-operations'

## Function 2 - torch.logspace

torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

Creates a one-dimensional tensor of size steps whose values are evenly spaced from base(start) to base(end) , inclusive, on a logarithmic scale with base(base)

In [ ]:
# Example 1 - working
t4 = torch.logspace(-10, 10, 5)
t4

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

Explanation about example

In [ ]:
# Example 2 - working
t5 = torch.logspace(0.1, 1.0, 5)
t5

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.logspace(10, 0)

tensor([1.0000e+10, 7.9248e+09, 6.2803e+09, 4.9770e+09, 3.9442e+09, 3.1257e+09,
        2.4771e+09, 1.9630e+09, 1.5557e+09, 1.2328e+09, 9.7701e+08, 7.7426e+08,
        6.1359e+08, 4.8626e+08, 3.8535e+08, 3.0539e+08, 2.4201e+08, 1.9179e+08,
        1.5199e+08, 1.2045e+08, 9.5455e+07, 7.5646e+07, 5.9948e+07, 4.7508e+07,
        3.7649e+07, 2.9836e+07, 2.3645e+07, 1.8738e+07, 1.4850e+07, 1.1768e+07,
        9.3260e+06, 7.3907e+06, 5.8570e+06, 4.6416e+06, 3.6784e+06, 2.9151e+06,
        2.3101e+06, 1.8307e+06, 1.4508e+06, 1.1498e+06, 9.1116e+05, 7.2208e+05,
        5.7224e+05, 4.5349e+05, 3.5938e+05, 2.8480e+05, 2.2570e+05, 1.7886e+05,
        1.4175e+05, 1.1233e+05, 8.9022e+04, 7.0548e+04, 5.5908e+04, 4.4306e+04,
        3.5112e+04, 2.7826e+04, 2.2051e+04, 1.7475e+04, 1.3849e+04, 1.0975e+04,
        8.6975e+03, 6.8926e+03, 5.4623e+03, 4.3288e+03, 3.4305e+03, 2.7186e+03,
        2.1544e+03, 1.7074e+03, 1.3530e+03, 1.0723e+03, 8.4975e+02, 6.7342e+02,
        5.3367e+02, 4.2292e+02, 3.3516e+

Explanation about example

Closing comments about when to use this function

This function is used to create torch arrays when the elements are needed to be logarithmicly spaced inbetween.



In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ddmasterdon/01-tensor-operations


'https://jovian.ai/ddmasterdon/01-tensor-operations'

## Function 3 - torch.cat

torch.cat(tensors, dim=0, *, out=None) → Tensor

Concatenates the given sequence of `seq` tensors in the given dimension.

In [ ]:
# Example 1 - working
x = torch.randn(2,3)
t7 = torch.cat((x, x, x), 1)
t7

tensor([[ 0.1392,  0.3485,  0.3953,  0.1392,  0.3485,  0.3953,  0.1392,  0.3485,
          0.3953],
        [ 1.1192, -0.4694, -2.2480,  1.1192, -0.4694, -2.2480,  1.1192, -0.4694,
         -2.2480]])

Explanation about example

In [ ]:
# Example 2 - working
y = torch.ones(2, 3)
z = torch.zeros(2, 3)
t8 = torch.cat((y, z, y, z), 1)
t8

tensor([[1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((x, y), 2)

IndexError: ignored

This functions accepts a dimension of -2 to 1

Closing comments about when to use this function

This function is great while joining to or more tensors when the required dimension is inbetween 0 and 1

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ddmasterdon/01-tensor-operations


'https://jovian.ai/ddmasterdon/01-tensor-operations'

## Function 4 - torch.reshape

torch.reshape(input, shape) → Tensor

Returns a tensor with the same data and number of elements as `input`, but with the specified shape. When possible, the returned tensor will be a view of `input`.

In [ ]:
# Example 1 - working
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

Explanation about example

In [ ]:
# Example 2 - working
b = torch.zeros(2, 9)
b.reshape(2, 3, 3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.ones(4, 7)
c.reshape(2, 3, 3)

RuntimeError: ignored

Explanation about example

Shapes should match

Closing comments about when to use this function

This function is great in reshaping tensors

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ddmasterdon/01-tensor-operations


'https://jovian.ai/ddmasterdon/01-tensor-operations'

## Function 5 - torch.normal

torch.normal(mean, std, *, generator=None, out=None) → Tensor

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

In [ ]:
# Example 1 - working
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 0.2759,  2.2800,  4.1324,  4.5404,  5.8416,  5.2365,  7.4910,  7.8157,
         9.1654, 10.0829])

In [ ]:
# Example 2 - working
torch.normal(torch.arange(1., 21.), torch.arange(2.,4., 0.1))

tensor([ 0.9215,  2.3606,  3.7136,  6.5101,  5.5224,  6.6937,  3.7683,  8.1205,
         7.1825, 11.4267,  9.9075,  7.0138, 10.4722, 15.0258, 19.0669, 26.1746,
        22.2663, 15.5832, 14.9466, 17.4243])

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(torch.arange(1., 11.), torch.arange(2.,4., 0.1))

RuntimeError: ignored

Explanation about example

Input shapes of mean and standard deviation sould match

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ddmasterdon/01-tensor-operations


'https://jovian.ai/ddmasterdon/01-tensor-operations'

## Conclusion

This notebook contains 5 usefull PyTorch 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
